#!/bin/busybox sh
set -x

/bin/busybox --install -s /bin

mkdir -p /dev /boot /mnt/ro /mnt/rw /proc /sys /etc /tmp

touch /etc/fstab

mount -t devtmpfs none /dev
mount -t sysfs none /sys
mount -t proc none /proc
mount -t tmpfs -o size=50M none /tmp

mount /dev/mmcblk0p1 /boot
cp /boot/filesystem.squashfs /tmp
umount /boot

mount -t squashfs /tmp/filesystem.squashfs /mnt/ro
mount -t tmpfs size=256M none /mnt/rw
mkdir /mnt/rw/upper /mnt/rw/work
mount -t overlay \
	-o lowerdir=/mnt/ro,upperdir=/mnt/rw/upper,workdir=/mnt/rw/work \
	overlay /mnt/overlay

mount --move /dev /mnt/overlay dev
umount /proc /sys

exec /bin/sh
