#!/bin/busybox sh
set -x

/bin/busybox --install -s /bin

mkdir -p /dev /boot /mnt /proc /sys /etc /tmp

touch /etc/fstab

mount -t devtmpfs none /dev
mount -t sysfs none /sys
mount -t proc none /proc
mount -t tmpfs -o size=50M none /tmp

mount /dev/mmcblk0p1 /boot
cp /boot/filesystem.squashfs /tmp
umount /boot

mount -t squashfs /tmp/filesystem.squashfs /mnt

exec /bin/sh
